// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgaceukqwfemqeygmbly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnYWNldWtxd2ZlbXFleWdtYmx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTI0ODAsImV4cCI6MjA2NTE2ODQ4MH0.pOyuBGP8-ExCnp4XXTZ6gNhXEDzi5kkk7GyP6Z0SWFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);